# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagesNavigate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowImages(object):
    def setupUi(self, MainWindowImages):
        MainWindowImages.setObjectName("MainWindowImages")
        MainWindowImages.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindowImages)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(10, 10, 461, 321))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("assets/cat.jpg"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.btn_cat = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cat.setGeometry(QtCore.QRect(60, 350, 101, 41))
        self.btn_cat.setObjectName("btn_cat")
        self.btn_dog = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dog.setGeometry(QtCore.QRect(310, 350, 101, 41))
        self.btn_dog.setObjectName("btn_dog")
        MainWindowImages.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowImages)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindowImages.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowImages)
        self.statusbar.setObjectName("statusbar")
        MainWindowImages.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowImages)
        QtCore.QMetaObject.connectSlotsByName(MainWindowImages)
        
    ###############Codigo adicionado apos a criação no QTDesigner###############
        self.btn_cat.clicked.connect(self.show_cat)
        self.btn_dog.clicked.connect(self.show_dog)
        
        
    def show_cat(self):
        self.Image.setPixmap(QtGui.QPixmap("assets/cat.jpg"))
    def show_dog(self):
        self.Image.setPixmap(QtGui.QPixmap("assets/dog.jpg"))
        
    ###############Criado apos a criação no QTDesigner###############

    def retranslateUi(self, MainWindowImages):
        _translate = QtCore.QCoreApplication.translate
        MainWindowImages.setWindowTitle(_translate("MainWindowImages", "MainWindowImages"))
        self.btn_cat.setText(_translate("MainWindowImages", "CAT"))
        self.btn_dog.setText(_translate("MainWindowImages", "DOG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowImages = QtWidgets.QMainWindow()
    ui = Ui_MainWindowImages()
    ui.setupUi(MainWindowImages)
    MainWindowImages.show()
    sys.exit(app.exec_())
